### ISSUE TITLE
Building .exe

### ISSUE THREAD

**Issue by salarmehr** [stefan-loewe/WinBinder#11]
What is the common way to make an exe file from a WinBinder application? 
Is there any place to downlaod possible desktop apps build by WindBinder? 

Thanks.

**Comment by stefan-loewe** [comment]
There is something like a show-case app for Woody, a OOP library I built on top of winbinder.

See https://github.com/stefan-loewe/BattMan. It uses composer, so you can pull all dependencies easily.

If you run into issues, please open up a issue there.

There used to be apps available at http://winbinder.org/forum/ and http://winbinder.quickphpbb.com/, but both forums are down. The latter was up until recently, so maybe it comes back.

Cheers
Stefan

**Comment by salarmehr** [comment]
There was a tool to make .exe file for WinBinder several years ago. Unfortunaely, I don't remember its name.

**Comment by stefan-loewe** [comment]
You probably mean bamcompiler, which is php4 only - won't work.

I know of no way to make exe's for WinBinder, that would work.

Packing it in an phar file is an option.

**Comment by stefan-loewe** [comment]
There is also https://github.com/alecgorge/phpack - which was built for WinBinder.

Not sure if it still works - when I tried it, I did not get it to work. Did not try too long though ...

**Comment by RainbowDashDC** [comment]
I rebulit phc-win awhile back, but it doesn't support automatically adding more than one file you have to type the embeder commands from that. See https://github.com/RDashINC/phc-win

**Comment by RainbowDashDC** [comment]
And embeder2 fork to actually be buildable: https://github.com/rdashinc/embeder2

**Comment by Kankrelune** [comment]
Else a simple alternative is to create a batch launcher who call your php files and compile it with a software such as Bat To Exe Converter. You can put a part of the executed code in the launcher for hide it, add included files in the exe file. Of course it's just an alternative, you can't really hide all your source code (if that's your goal) but the advantage is you can re-edit your code without having to recompile everything each time.

**Comment by RainbowDashDC** [comment]
@Kankrelune That doesn't work because PHP isn't embedded itself, plus that route doesn't end well-- I've tried it. Its all extracted to %TMP% which is unnecessary io.

**Comment by Kankrelune** [comment]
I've never say you can embed PHP itself in the exe file... you can but it's not a usefull way and as you say if you use the embedded file capability (in the tmp but you can extract the files in the current working dir) you must dynamically define your include path, a simple dirname(__FILE__) and it's ok it's not a problem... but as I've said that's not the goal of this alternative. This alternative is just for have an exe launcher and eventually for hide a little part of the code (php -r ...).

**Comment by Encorn** [comment]
It can't be that hard to bring bambalam compiler to PHP5.

**Comment by RainbowDashDC** [comment]
Closing, this is not WinBinder's issue, however feel free to continue conversing about the topic.
