### ISSUE TITLE
PHP7 Support

### ISSUE THREAD

**Issue by darkphase** [stefan-loewe/WinBinder#13]
Is PHP7 support coming?

**Comment by jaredallard** [comment]
I'm not sure, I might be able to use the little C & C++ knowledge I have to incorporate it, but I would not count on it if PHP7 has __*major*__ API changes.

**Comment by stefan-loewe** [comment]
I second that. I might have a look into this once PHP 7 is final, but not before that - unless I am really really bored, which just won't happen.

There might be some asynchronous programming coming with PHP 7, depending on how that looks and works, this sure could be interesting for UI programming ... we'll see.

**Comment by darkphase** [comment]
good to hear...

**Comment by Darksynx** [comment]
PHP 7.0 (7.0.0beta1)
http://windows.php.net/qa

is time for create new winbinder 2.0 .

**Comment by jaredallard** [comment]
I'll see about it later tonight, and if it requires drastic changes. If it does, and I'm willing, I'll create either another branch, or another repository for the 7.0 extension.

**Comment by darkphase** [comment]
Probably we need to setup VC14. Right?

**Comment by Darksynx** [comment]
good news !! winbinder 2.0 with new color management transparency and displays skin office type menu ^^

**Comment by jaredallard** [comment]
Will look into today

**Comment by Darksynx** [comment]
we can create a graphical interface based on html. to completely detach from windows, winbinder 3 should simply be compatible png / jpg, wav / mp3 / ogg and mp4. From here everything has around will winbinder external modules: menu, transparency, skin management etc ...

**Comment by jaredallard** [comment]
Are you thinking something like NW.js?

**Comment by Darksynx** [comment]
for my part, NW.js is still too experimental to serve as a solid foundation. VC ++ would be best or .net.

**Comment by jaredallard** [comment]
No, I'm just asking if that's the concept you're thinking of.

I was thinking something sorta like that.

**Comment by jaredallard** [comment]
Webkit + PHP in the DOM.

**Comment by Darksynx** [comment]
Qtweb is cool browser light and 0 skin , compatibly css , html5 and java . 
http://cluster003.ovh.net/~duplifil/qt/qtweb_light_test.zip
Qtweb + PHP7 

I did not find web browser smallest and as complete as QtWeb. that could be a good visual aid for PHP7.
I have not tested anything yet. I configured QT web ultre light mode to display only a single web page
I think it is unnecessary to reinvent the wheel but if anyone seen dévelloper ultra light web explorer, Winbinder -> WinWebKit ^^> WWK here is a good basis for the continuation of winbinder. we forget the usual system and leave on a principle dialogy client <-> server snapshot. much like the principle of irc ..

**Comment by darkphase** [comment]
I may agree with the whole, "a PHP extension can manage browser windows & access the DOM" (like nodejs counterparts ) concept but, that would be totally different project.

**Comment by jaredallard** [comment]
I may work on a project for that. Would allow cross compat php apps

**Comment by darkphase** [comment]
Please open the project & let us watch it then... We're (At least I'm) eagerly awaiting...
As of now using app.js + mongoose webserver + php-cgi for the job.
Single "PHP7" extension would be terrific.

**Comment by jaredallard** [comment]
@darkphase the big problem is I am in no way a C dev. Though maybe I can get something done!

**Comment by jaredallard** [comment]
Or, perhaps some other method of working with this.

**Comment by Darksynx** [comment]
as long as PHP can display dialog boxes in html using a microphone embedded web browser, we just do everything and compatibility hand will do only one software naviagteur the microphone that dialogue with php. and PHP will not be diverted from its initial objective. after I could not dévelloper micro browser I am expert PHP ^^ there I am dependent on you DEV C, C ++. php side I already work on a client / server that replaces Apache ...

**Comment by Darksynx** [comment]
OMG oO ... http://php.net/manual/fr/features.commandline.webserver.php

**Comment by Darksynx** [comment]
http://cluster003.ovh.net/~duplifil/qt/Proton_project.zip , php-webserv . and with php_pthreads.dll i can thread and controle browseur

**Comment by darkphase** [comment]
I figured that much...
