### ISSUE TITLE
Where can I find your latest changelog?

### ISSUE THREAD

**Issue by brittainmedia** [stefan-loewe/WinBinder#14]
I recently moved to your extension for its php version compatibility. What have you focused on changing/updating in this version?

Thanks

**Comment by jaredallard** [comment]
Hey! Most of the stuff done right now is just making sure original WinBinder works, and supports PHP version.

In terms of features-- well, @stefan-loewe and I are not C or CPP programmers. However, I am working to learn C, so I may work on adding new stuff, mostly by request!

We have no changelog for now, when we do start version tracking them I will make a CHANGELOG.md. Thanks for you interest!
