### ISSUE TITLE
PHP7 Support!

### ISSUE THREAD

**Issue by jaredallard** [stefan-loewe/WinBinder#15]
Here's a list of issues behind PHP 7 support:
- [x] win32std works with PHP 7 (https://github.com/rdashinc/win32std/tree/php7)
- [x] ZEND_REGISTER_RESOURCE -> zend_register_resource2[_ex] 
- [x] Use `Z_TYPE_P`, `Z_STRVAL_P`, `Z_STRLEN_P`, macros instead of manually retrieving struct.
- [x] Fix process_array()

_wb_lowlevel.cpp_
- [ ] use `sprintf_s` instead of `sprint` for safety.

_Track the changes on branch "**php7**"!_

**Comment by acuna-personal** [comment]
Hello! Does it working with PHP 7 or not? See one commit about it, but it's revert...

**Comment by jaredallard** [comment]
It's in a separate branch and *should* work. Never fully tested it if I remember correctly, been awhile.

On Mon, Mar 27, 2017, 12:34 PM Антон Тихомиров <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello! Does it working with PHP 7 or not? See one commit about it, but it's revert...

**Comment by acuna-personal** [comment]
Ah, okay, think I'll test it for my purposes when've find the free time on it.

**Comment by acuna-personal** [comment]
Ah yes, and I wanted to ask you, is it your own project or not? Why it isn't added to PECL repository, is it because it not fully tested?

**Comment by jaredallard** [comment]
@acuna-personal This is a fork of the old WinBinder. No idea why it's not on PECL. I don't use PHP anymore to be honest.

**Comment by acuna-personal** [comment]
Aaaah, it's not yours, I seee... Okay, thanks)

**Comment by stefan-loewe** [comment]
It is "mine" - in the sense that it is my repo on github. Feel free to fork it, put in on PECL etc.

I put it here from http://winbinder.org/ long time ago, after kind permission from Rubem Pechansky, the original author, to somehow get contributors on this project. But it did not really take off, hehe.

It is also on PECL https://pecl.php.net/package/WinBinder but outdated.

**Comment by acuna-personal** [comment]
Well, thanks, I think I'll try to test it deep and put it on PECL...
And can I ask you, why do you don't use the PHP anymore? Remarkable, that since PHP7 it's an other language in fact, its kernel was totally rewriten ant its speed now comparable with raw Assembler concider, so now it's not a personal home page tools bundle, it's... It's an C++ Framework which is take all dirty work on it)

**Comment by jaredallard** [comment]
I stopped using PHP for node a while back. Haven't even tried php7 yet. I may consider expanding, but Ruby would be what's popular around here or perl ;)

**Comment by acuna-personal** [comment]
Hohoooo, I think there's no any sense to compare the PHP (!) and Ruby/Perl (!!) communities by its sizes :DDD

**Comment by acuna-personal** [comment]
I mean that PHP community is the biggest one in the world, its not a joke :/

**Comment by stefan-loewe** [comment]
this will not be fixed in this repo, but user wagy has a fork, from where a working version with PHP 7 is available - be sure to check it out at https://github.com/wagy/WinBinder
