### ISSUE TITLE
hello, how to call EnumWindows function in use32.dll , it's has a callback.

### ISSUE THREAD

**Issue by happyxlq** [stefan-loewe/WinBinder#16]
include PATH_INC . "winbinder.php";

$USER = wb_load_library("USER");

$cb =  wb_get_enum_callback();
$pfn = wb_get_function_address("EnumWindows", $USER);

$d =  wb_call_function($pfn, array($cb, ''));

var_dump($d); // return 0;

please help..

**Comment by brittainmedia** [comment]
If the function fails, the return value is zero. To get extended error information, call GetLastError.

If EnumWindowsProc returns zero, the return value is also zero. In this case, the callback function should call SetLastError to obtain a meaningful error code to be returned to the caller of EnumWindows.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms633497(v=vs.85).aspx

**Comment by happyxlq** [comment]
thanks, but in php ,in winbinder  no GetLastError function...

**Comment by happyxlq** [comment]
`
<?php
// STEP 1: Create main window

$mainwin = wb_create_window(NULL, AppWindow, "Five steps", 320, 240);

wb_set_handler($mainwin, "process_main");

$USER = wb_load_library("USER");

$cb =  wb_get_enum_callback();

$pfn = wb_get_function_address("EnumWindows", $USER);

$d =  wb_call_function($pfn, array($cb, ''));


function process_main($window, $id, $e, $f, $g, $h) {
  var_dump($f):
}
`
this works!..but not good

**Comment by brittainmedia** [comment]
`$Kernel32 = wb_load_library("Kernel32");

$LastErrorPfn = wb_get_function_address("GetLastError", $Kernel32);

$lastError = wb_call_function($LastErrorPfn, array());

var_dump($lastError);`

You can see roughly what the error codes mean by cross referencing it with the constant name:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx

P.S I tested your code, and it appeared to work correctly for me, but I am using a modified version of the WinApi wrapper a fellow Stefan made: https://github.com/stefan-loewe/Woody/tree/master/source/ws/loewe/Woody/Util/WinApi

**Comment by stefan-loewe** [comment]
seems to be closed - thanks for the support!
