### ISSUE TITLE
Recent Releases

### ISSUE THREAD

**Issue by ostapski** [stefan-loewe/WinBinder#18]
Hi ..

Just a question ... whats the point releasing all in VC13 ... when 5.5 and 5.6 are compiled with VC11 ?
all released DLLs refuse to load...

**Comment by Darksynx** [comment]
If you use an executable compiler in VC11
Use dll compile in VC11 otherwise it does not work.
By chance I have already compiled:

https://github.com/Darksynx/WinBinder/releases

**Comment by ostapski** [comment]
Hi ..

brilliant .. :) .. you are just few hours too late ...
I’ve moved from 5.3.5 ... to 5.4.16 ...  it accepted the old version and ... what actually it was about ... the “threads”  dll ... (threads extension wouldn’t load on 5.3.5... so I started testing latest versions of PHP..)
Even tried to compile your source ... and failed ... (VC doesn’t like much .c code ...without proper settings in project)

But this is great too ... !! .. 
I’m using PHP as a wrapper for gaming servers ... and winbinder  is essential to send messages to the server..(from other managing script or website)
I’m going try your new release 

Thank you for such prompt response ...!!

Best regards,
Alexandre Ostanine.

PS.. 
Just a question ... since all I needed works in 5.4 ... I tried today to use winbinder in main PHP thread ...and the child one...
but ...as soon I called the Kernel32::function from the child thread ...  - whole script crashes ....(no errors btw ...nowhere to find...just silent termination.)

I tried to load the dll’s again ... from within the child thread...I thought maybe child thread doesn’t have the pointers right ...or something ..(with minor modifications to the “WinAPI.php” script ... to avoid duplicate class definitions) but with no success at the moment ...

My goal is to run parallel thread that would listen for incoming messages.. .(posted from server ... with PostThreadMessage)
I can post ..thanx to winbinder ... ... now I’d like to receive ... asynchronously ...

Any thoughts on how to fix that ?...

**Comment by Darksynx** [comment]
http://www.mediafire.com/file/5gbih567kuce7ef/php_5.6.30_vc11_with-winbinder.rar

Uses my version, it is a special php executable that will execute the file init.php, winbinder is already integrating to the php libraries 5.6.30. If you need to add extensions, take the extensions of this archive: http://windows.php.net/downloads/releases/archives/php-5.6.30-Win32-VC11-x86.zip.

Normally you will no longer have to bug. The 5.6.30 is the most stable version of php.

**Comment by ostapski** [comment]
Hi Stefan 

It all works now !!
I’m moved to 5.6 .... with latest winbinder and other required extensions ....
All works ... 
I can send to the game thread ...and successfully receive messages inside a child thread created by main php script ...
so far – no hiccups ...

Best Regards,
Alexandre Ostanine.

**Comment by stefan-loewe** [comment]
this seems to be fixed, thanks for the support
