### ISSUE TITLE
Create a gitter

### ISSUE THREAD

**Issue by RainbowDashDC** [stefan-loewe/WinBinder#7]
It'd be nice to have a http://gitter.im/

**Comment by Encorn** [comment]
I think it would be unused most of the time.

**Comment by RainbowDashDC** [comment]
Still useful to have one.

**Comment by stefan-loewe** [comment]
Hey guys. While I agree with Encorn, I also do not see why not to have that.

However, I do not have much time to work on this project other then not letting it die ...

So, anybody want to become a contributor. in this case, I assume, you could also merge pull requests yourself, and integrate gitter.im, I assume.

I am still around, but more on the PHP side (my Woody project) than the C side (this repo)

Any takers?

Cheers
Stefan

**Comment by RainbowDashDC** [comment]
I'd be full willing to take over this project.

**Comment by stefan-loewe** [comment]
RainbowDashDC, I made you a contributor - you should now have more rights. Not sure how far that goes.

if you have other ideas how to increase your "rank", please tell me - not very into github regarding stuff like that.

Cheers
Stefan

**Comment by RainbowDashDC** [comment]
@stefan-loewe Thank you! And contrib is the best and all I need. 

I've added a gitter so I'll mark this closed.
